pizzy_project/app1/urls.py
from django.urls import path

from .views import ProfileView, AccueilView, LB_create, LB_detail


app_name = 'app1'
urlpatterns = [
    path('', AccueilView.as_view(), name='accueil'),

    path('accounts/profile/', ProfileView.as_view(), name='profile'),

    path('create-lb/', LB_create.as_view(), name='create-lb'),
    path('detail-lb/<int:pk>/', LB_detail.as_view(), name='detail-lb'),

]    

pizzy_project/pizzy_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls',)),
    path('', include('users.urls')),
]

pizzy_project/users/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.views.generic import RedirectView
from django.urls import  reverse_lazy
from .views import PasswordResetView, PasswordResetConfirmView, LogoutView, SignUpView, Activate, LoginView

app_name = 'users'                            

urlpatterns = [
    path('',  RedirectView.as_view(url=reverse_lazy('app1:index')), name='index'),
    path('login', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', Activate.as_view(), name='activate'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), 
                                                                name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), 
                                                                        name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

pizzy_project/app1/models.py
from django.db import models

from users.models import User

# Create your models here.

class Teatcher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    isIndependant = models.BooleanField(default=False, verbose_name="independant")
    
    def __str__(self):
        return 'Teatcher ' + self.user.username

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(null=True, verbose_name="date de naissance")
    def __str__(self):
        return 'TeaStudenttcher ' + self.user.username

#..........

class Discipline(models.Model):
    libelle = models.CharField(max_length=100)
    def __str__(self):
        return self.libelle

class LearnBox(models.Model):
    libelle = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=500)
    owner = models.ForeignKey(Teatcher, on_delete=models.CASCADE)
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)

pizzy_project/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.views.generic import View, DetailView, ListView, TemplateView, CreateView
from .models import *

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy

def home(request):
    return HttpResponse('You are at home')

class AccueilView(TemplateView):
    template_name = "app1/accueil.html"

login_required_m = megit log thod_decorator(login_required)
class ProfileViegit pullw(View): # TODO ? RedirectView

    @login_required_m
    def get(self, request):

        isTeatcher = Teatcher.objects.filter(user=request.user).count() > 0

        if isTeatcher :
            teatcher = Teatcher.objects.get(user=request.user)
            lboxes = LearnBox.objects.filter(owner=teatcher)
            
            return render(request, "app1/teatcher_detail.html", {'lboxes' : lboxes})
        else:
            return render(request, "app1/student_detail.html", {})

login_required_m = method_decorator(login_required)
class LB_create(CreateView):
    model = LearnBox
    fields = ['libelle', 'description', 'discipline']
    success_url = reverse_lazy('app1:profile')
    success_message = "LearnBox crée"

    def form_valid(self, form):
        teatcher = Teatcher.objects.get(user=self.request.user)
        form.instance.owner = teatcher
        return super(CreateLBView, self).form_valid(form)


login_required_m = method_decorator(login_required)
class LB_detail(DetailView):
    model = LearnBox

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['book_list'] = Book.objects.all()
    #     return context

pizzy_project/app1/templates/app1/accueil.html
Page d'accueil
<br>
<a href="{% url 'users:login' %}" >Se logger</a>

pizzy_project/app1/templates/app1/base_student.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>{% block title %}Pizzy{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> 

    <!-- FavIcon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/signup.css' %}" />
    <link rel="stylesheet" type="text/css" href= {% block css %} {% endblock css %} />
    {% block head %}
    {% endblock %}
    
</head>

<body id="body_base" class="container">
    
    <header class="row">
            <a href="{% url 'users:index' %}"><img id="logo_pizzy" src="{% static 'img/logo_pizzy.jpg' %}" alt="PIZZY"></a>
            <div id="titre_base">Bonjour {{user.username}}</div>
    </header>

    <div>
        {% if user.is_authenticated %}
        <navbar class="row">
            <nav id="navbar" class="site-header sticky-top py-1 col-md-12">
                <div id="filtre_url_navbar" class="container d-flex flex-column flex-md-row justify-content-between">
                    <a href="{% url 'users:logout' %}" class="btn fas fa-sign-out-alt" id="logout" title="Déconnexion">Déconnexion</a>
                </div>
            </nav>
        </navbar>
        {% else %}
        <div class="row">
                <div class="col-md-12" id="bandeau_footer"></div>
        </div>
        {% endif %}
    </div>

    <div>
        {% block section %}
        {% endblock %}
    </div> 

    <footer>
    </footer>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/vue.js' %}"></script> -->

</body>

</html>

pizzy_project/app1/templates/app1/base_teatcher.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>{% block title %}Pizzy{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> 

    <!-- FavIcon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/signup.css' %}" />
    <link rel="stylesheet" type="text/css" href= {% block css %} {% endblock css %} />
    {% block head %}
    {% endblock %}
    
</head>

<body id="body_base" class="container">
    
    <header class="row">
            <a href="{% url 'users:index' %}"><img id="logo_pizzy" src="{% static 'img/logo_pizzy.jpg' %}" alt="PIZZY"></a>
            <div id="titre_base">Enseignants : Tableau de bord</div>
    </header>

    <div>
        {% if user.is_authenticated %}
        <navbar class="row">
            <nav id="navbar" class="site-header sticky-top py-1 col-md-12">
                <div id="filtre_url_navbar" class="container d-flex flex-column flex-md-row justify-content-between">
                    <a href="{% url 'users:logout' %}" class="btn fas fa-sign-out-alt" id="logout" title="Déconnexion">Déconnexion</a>
                </div>
            </nav>
        </navbar>
        {% else %}
        <div class="row">
                <div class="col-md-12" id="bandeau_footer"></div>
        </div>
        {% endif %}
    </div>

    <div>
        {% block section %}
        {% endblock %}
    </div> 

    <footer>
    </footer>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/vue.js' %}"></script> -->

</body>

</html>

pizzy_project/app1/templates/app1/student_detail.html
{% extends 'app1/base_student.html' %}


{% block section %}


Bonjour {{ user.username }}

    
</div> 


{% endblock %}

pizzy_project/app1/templates/app1/teatcher_detail.html
{% extends 'app1/base_teatcher.html' %}


{% block head %}
{% endblock %}

{% block section %}

<div class="row">
    <p>
        Tableau de bord de {{user.username }} ({{user.email}}) <br>

        <a href="{% url 'app1:create-lb' %}">Créer une LB</a>
        
        <br><br>
        
        Liste des LB <br>
    
        {% for lb in lboxes %}
        <a href="{{ lb.get_absolute_url }}">{{lb.libelle}}</a> <br>
        {% endfor %}
    
    </p>
</div> 


{% endblock %}

pizzy_project/app1/templates/app1/toto.html
Vous êtes : {{ user.username }}