pizzy_project/app1/urls.py
from django.urls import path

from .views import ProfileView, AccueilView, LB_create, LB_detail


app_name = 'app1'
urlpatterns = [
    path('', AccueilView.as_view(), name='accueil'),

    path('accounts/profile/', ProfileView.as_view(), name='profile'),

    path('create-lb/', LB_create.as_view(), name='create-lb'),
    path('detail-lb/<int:pk>/', LB_detail.as_view(), name='detail-lb'),

]    

pizzy_project/pizzy_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls',)),
    path('', include('users.urls')),
]

pizzy_project/users/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.views.generic import RedirectView
from django.urls import  reverse_lazy
from .views import PasswordResetView, PasswordResetConfirmView, LogoutView, SignUpView, Activate, LoginView

app_name = 'users'                            

urlpatterns = [
    path('',  RedirectView.as_view(url=reverse_lazy('app1:index')), name='index'),
    path('login', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', Activate.as_view(), name='activate'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), 
                                                                name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), 
                                                                        name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

pizzy_project/users/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from django.conf import settings

from .managers import UserManager

class User(AbstractBaseUser):
    email             = models.EmailField(max_length=255, unique=True, verbose_name='Adresse Email')
    username          = models.CharField(max_length=15, unique=True, verbose_name='Pseudo',)
    first_name        = models.CharField(max_length=30, verbose_name='Prénom')
    last_name         = models.CharField(max_length=50, verbose_name='Nom')
    
    is_active         = models.BooleanField(default=True, verbose_name='Utilisateur actif')
    is_staff          = models.BooleanField(default=False, verbose_name="Staff")
    is_admin          = models.BooleanField(default=False, verbose_name='Admin')
    date_joined       = models.DateTimeField(editable=False, default=timezone.now)
    first_connection  = models.BooleanField(default=True, verbose_name='Premiere connection')

    confirm           = models.BooleanField(default=False)
    confirmation_date = models.DateTimeField(null=True)

    class Meta:
        verbose_name = "Pizzy Utilisateur"
        verbose_name_plural = "Pizzy Utilisateurs"

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserManager()

    def get_full_name(self):
        full_name = '{} {}'.format(self.first_name, self.last_name)
        return full_name.strip()
        
    def get_short_name(self):
        return self.first_name + '#'+ str( self.pk )
    
    def __str__(self):
        return 'User-> '+ self.email

    def has_perm(self, perm, obj=None):
        """ Does the user have a specific permission? """
        return True

    def has_module_perms(self, app_label):
        """ Does the user have permission to view the app 'app_label' """
        return True

class PrivateData(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE, related_name='private_data')
    phone_number    = models.CharField(max_length=20)

    def __str__(self):
        return "Données Privées de : " + str(self.user) 

class UserProfile(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    # driver_license  = models.BooleanField(default=False, verbose_name="permis",
    #                                     choices=( (True, "Oui"), (False, "Non")) )
    # trainee         = models.BooleanField(default=False, verbose_name="statut",
    #                                     choices=( (True, "Stagiaire"),(False, "Employé") ))
    # car_owner       = models.BooleanField(default=False, verbose_name="Propriétaire d'un Véhicule",
    #                                     choices=( (True, "Oui"), (False, "Non")) )
    profile_image   = models.ImageField(blank=True, upload_to='avatars/', default='avatar_generique.jpg')
    # smoker          = models.BooleanField(default=False, verbose_name="Fumeur",
    #                                     choices=( (True, "Fumeur"), (False, 'Non Fumeur')))
    # talker          = models.BooleanField(default=False, verbose_name="Bavard",
    #                                     choices=( (True, "Bavard"), (False, 'Peu Bavard')))
    # music           = models.BooleanField(default=False, verbose_name="Musique",
    #                                     choices=( (True, "Oui"), (False, 'Non')))
    gender          = models.CharField(max_length=50, default='None',choices=(
                                        ('None', "Non communiqué"),
                                        ('Woman', "Femme"),
                                        ('Man', "Homme"),),)

    def __str__(self):
        return "Profile de : " + str(self.user)


def create_user_data(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        PrivateData.objects.create(user=instance)

post_save.connect(create_user_data, sender=settings.AUTH_USER_MODEL )

pizzy_project/users/forms.py
from django import forms
from django.contrib.auth import authenticate, password_validation
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import (ReadOnlyPasswordHashField, PasswordChangeForm as BasePasswordChangeForm, 
                                        PasswordResetForm as BasePasswordResetForm, 
                                        SetPasswordForm as BaseSetPasswordForm)
from django.forms import TextInput, PasswordInput, EmailInput

from .models import User, PrivateData

class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'username', 'first_name', 'last_name', 'is_active', 'is_staff', 'is_admin')
        widgets = {
            'email': TextInput(attrs={'class': 'form-control'}),
            'first_name': TextInput(attrs={'class': 'form-control'}),
            'last_name': TextInput(attrs={'class': 'form-control'}),

        }
        labels = {
            'email': "Adresse Email",
            'first_name': "Prénom",
            'last_name': "Nom de famille",
        }

    password1   = forms.CharField(label="Mot de Passe",  widget=PasswordInput(attrs={'class': 'form-control'}))
    password2   = forms.CharField(label='Confirmation Mot de Passe', widget=PasswordInput(attrs={'class': 'form-control'}))
    username    = forms.RegexField(regex=r'^[\w._-]+$', label='Pseudonyme',
                                    min_length=3,
                                    error_messages = {'invalid': "Votre ne pseudonyme ne peut contenir que des lettres,"
                                    "nombres ou caractères suivants : ./_/-"},
                                    widget=TextInput(attrs={'class': 'form-control'}) )

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        user = User.objects.filter(email=email)
        if user.count():
            raise ValidationError("Cette adresse email est déjà utilisée sur le site")
        return email

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        user = User.objects.filter(username=username)
        if user.count():
            raise ValidationError("Pseudonyme existant")
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Les deux mots de passe ne correspondent pas")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class SignupForm(UserCreationForm):
    phone_number = forms.RegexField(regex=r'^[0+][\d]+$',label="Numéro de téléphone",
                                    min_length=10, max_length=13, 
                                    error_messages={'invalid': 'Numéro de téléphone invalide'}, 
                                    widget=TextInput(attrs={'class': 'form-control'}))


    class Meta(UserCreationForm.Meta):
        exclude = ('is_active', 'is_admin', 'is_staff')



class LoginForm(forms.Form):
    email = forms.EmailField(widget=EmailInput(attrs={'class':'form-control mb-3','placeholder': 'Adresse Email'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class':'form-control mb-3','placeholder': 'Mot de Passe'}))

    def __init__(self, request, *args, **kwargs):
        # do not pass 'request' to the parent
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        if email is not None and password:
            self.user = authenticate(username=email, password=password)
            if not self.user:
                raise forms.ValidationError("Vos identifiants ne correspondent pas")
            elif not self.user.is_active:
                raise forms.ValidationError("Veuillez confirmez votre adresse email")
        return self.cleaned_data

    def get_user(self):
        return self.user

class LogoutForm(forms.Form):
    pass

class SetPasswordForm(BaseSetPasswordForm):
    error_messages = {
            'password_mismatch': 'Les deux mots de passes ne sont pas identiques',
    }

    new_password1 = forms.CharField(
        label="Nouveau Mot de Passe",
        widget=forms.PasswordInput(attrs={'class': 'form-control require-input'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label="Confirmation",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control require-input'}),
    )

class PasswordChangeForm(SetPasswordForm, BasePasswordChangeForm, ):
    error_messages = {
            'password_incorrect': 'Ancien Mot de Passe incorrect',
    }

    old_password = forms.CharField(
        label="Ancien Mot de Passe",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control require-input', 'autofocus': True}),
    )

class PasswordResetForm(BasePasswordResetForm):
    email = forms.EmailField(label="Email", max_length=254, widget=TextInput(attrs={'class': 'form-control'}))

class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        fields = ('password', 'username', 'first_name', 'last_name', 'is_active', 'is_staff', 'is_admin')

    username   = forms.RegexField(regex=r'^[\w._-]+$', label='Pseudonyme',
                                    min_length=3,
                                    error_messages = {'invalid': "Votre ne pseudonyme ne peut contenir que des lettres,"
                                    "nombres ou caractères suivants : ./_/-"},
                                    widget=TextInput(attrs={'class': 'form-control'}) )

    def clean_password(self):
        return self.initial["password"]

pizzy_project/users/views.py
import datetime

from django.conf import settings
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash, get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.views import (PasswordResetView as BasePasswordResetView, PasswordResetDoneView, 
                                        PasswordResetConfirmView as BasePasswordResetConfirmView, PasswordResetCompleteView, 
                                        LogoutView as BaseLogoutView)
from django.core.mail import EmailMessage, EmailMultiAlternatives                                        
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_bytes, force_text
from django.utils.http import is_safe_url, urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, FormView, TemplateView, RedirectView

from .forms import LoginForm, SignupForm, LogoutForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from .tokens import account_activation_token
from pizzy_project.mixins import SendMailMixin

User = get_user_model()

settings.app_static_url = 'app1/{}'.format('app')

def index(request):
    return HttpResponse( ' Thou are at the index page')

class SignUpView(SendMailMixin, CreateView):
    template_name = "users/signup.html"
    form_class = SignupForm
    subject_template_name = 'users/activation_email_subject.txt'
    email_template_name = 'users/activation_email.html'
    from_email = None
    token_generator = account_activation_token

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()

        user.private_data.phone_number = form.cleaned_data["phone_number"]
        user.private_data.save()    
        user.user_profile.save() 

        # Envoie email de confirmation
        current_site = get_current_site(self.request)
        site_name = current_site.name
        domain = current_site.domain
        uid = urlsafe_base64_encode(force_bytes(user.pk)) #.decode()
        token = self.token_generator.make_token(user)
        use_https = self.request.is_secure()

        context = {
            'domain': domain,
            'site_name': site_name,
            'uid': uid,
            'token': token,
            'protocol': 'https' if use_https else 'http',
        }

        subject_template = self.subject_template_name
        email_template = self.email_template_name
        from_email = self.from_email
        email = user.email

        self.send_mail(
            subject_template, email_template, context, from_email,
            email,
        )

        return render(self.request, 'users/activation_link_send.html')

class Activate(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.confirm = True
            user.confirmation_date = timezone.now()
            user.save()
            return render(request, 'users/activation.html')
        else:
            return render(request, 'users/activation_link_invalid.html',)

class LoginView(BaseLoginView):
    form_class = LoginForm
    template_name = 'users/index.html' 
    redirect_field_name = 'roro'   

class LogoutView(FormView):
    form_class = LogoutForm
    template_name = 'users/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('users:index'))

class ChangePassword(View):
    template_name = 'users/password.html'

    def get(self, request):
        print(settings.app_static_url, "CHANGE PASSWORD ##############################")
        form = PasswordChangeForm(user=request.user)
        context = {
            'form': form, 
            'profil_url': 'TODO change',
        }
        return render(request, self.template_name, context )


    def post(self, request):
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('users:index')
        return render(request, self.template_name, {'form': form })

class PasswordResetView(BasePasswordResetView):
    email_template_name = 'users/password_reset_email.html'
    template_name = 'users/password_reset_form.html'
    success_url = reverse_lazy('users:password_reset_done')
    form_class = PasswordResetForm

class PasswordResetConfirmView(BasePasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')
    form_class = SetPasswordForm

pizzy_project/users/templates/users/activation.html
{% extends 'base.html' %}

{% block section %}

<div class="row">
    <p class="col-md-12 mt-3">Votre compte est activé !! Vous pouvez désormais vous <a href="">connecter</a>.
    </p>
</div>  

{% endblock %}

pizzy_project/users/templates/users/activation_email.html
{% autoescape off %}
Vous vous êtes récemment inscrit sur {{ site_name }}, merci de confirmer votre adresse email en cliquant sur le lien ci-dessous.

{{ protocol }}://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

Merci d'utiliser notre site.

The {{ site_name }} team

{% endautoescape %}

pizzy_project/users/templates/users/activation_link_invalid.html
{% extends 'base.html' %}

{% block section %}

<div class="row">
    <p class="col-md-12 mt-3">Ce lien d'activation n'est pas valide.
    </p>
    <p></p>
</div>  

{% endblock %}

pizzy_project/users/templates/users/activation_link_send.html
{% extends 'base.html' %}


{% block section %}


<div class="row">
    <p class="col-md-12 mt-3">Un courriel vous a été envoyé.</p>
    <p class="col-md-12">Merci de cliquer sur le lien contenu dans ce dernier afin de valider votre inscription.</p>

    
</div> 


{% endblock %}

pizzy_project/users/templates/users/index.html
{% extends 'base.html' %} 
{% load static %}

{% block css %} "{% static 'users/css/index.css' %}" {% endblock css %}

{% block section %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/index.css' %}" />
</head>

<body class="container">
    <div class="row">
        <div class="col-md-12" id="background_accueil">
    <div class="row">
        <div class="col-md-6">
            <div id="card1" class="card text-center" style="max-width: 18rem;">
                <div id="header_card1" class="card-header">Pas encore de compte ?</div>
                <div class="card-body">
                    <h5 id="sous_titre_card1" class="card-title">S'inscrire</h5>
                    <a href="{% url 'users:signup' %}"><button id="btn_card1" class="btn btn-success ">Créer un compte</button></a>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div id="card2" class="card text-center" style="max-width: 18rem;">
                <div id="header_card2" class="card-header">Déjà un compte ?</div>
                <div class="card-body">
                    <h5 class="card-title">Se connecter</h5>
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            {{ form.email }} 
                        </div>
                        <div>
                            {{ form.password }} 
                        </div>
                        {% if form.non_field_errors %}
                        <div id="error_login">
                            {% for error in form.non_field_errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        <button type="submit" class="btn btn-success mt-2 mb-2">Connexion</button>
                    </form>
                    <a id="reset-password" href="{% url 'users:password_reset' %}"> Mot de passe oublié ?</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12" id="espace_vide_accueil"></div>
    </div>  
</div>
</div>
</div>
</body>  



{% endblock %}

pizzy_project/users/templates/users/logout.html
{% extends "base.html" %}

{% block title %}Logout | {{ block.super }}{% endblock %}

{% block section %}
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <h3>Vous nous quittez déjà ?</h3>
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Se deconnecter" class="btn btn-success mb-5 mt-3">
            </form>
        </div>
        <div class="col-md-12" >
            <h5> Revenez vite !</h5>
            <p>Ce site fonctionne mieux si vous revenez souvent !</p>
        </div>
    </div>
</div>
{% endblock section %}

pizzy_project/users/templates/users/password.html
TODO template from carpooling/profil/password.html

pizzy_project/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block section %}


<div class="row">
    <p class="col-md-12 mt-3">{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
</div>  

<div class='row'>
    <div class="col-md-12">
        <a class='btn btn-success mb-3' href="{{ login_url }}">{% trans 'Log in' %}</a>
    </div>
</div>




{% endblock %}

pizzy_project/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n static %}


{% block section %}

{% if validlink %}

<div class='row'>

    <p class="col-md-12 mt-3">{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

</div>

<div class="row">
    <div class="col-md-4 mt-4"></div>

    <form class="col-md-8" method="post">
        {% csrf_token %}

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div id="header_input_profil" class="input-group-text">Nouveau mot de passe</div>
        </div>
        {{ form.new_password1 }}
        {{ form.new_password1.errors }}
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div id="header_input_profil" class="input-group-text">Confirmation du mot de passe</div>
        </div>
        {{ form.new_password2 }}
        {{ form.new_password2.errors }}
    </div>

    <div class='row'>
            <div class="col-md-2 mt-4"></div>
        <div id="submit_profil1">
            <button type="submit" class="btn btn-success mb-3">Envoyer</button>
        </div>
    </div>

    </form>
</div>

{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

pizzy_project/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block section %}
<div class='container'>

    <div class='row'>
        <p class='col-md-12 mt-3'>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

        <p class='col-md-12 mb-3'>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
    </div>

</div>



{% endblock %}

pizzy_project/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

pizzy_project/users/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load i18n static %}

{% block section %}

<div class='container'>

    <div class='row'>
        <p class='col-md-12 mt-3'>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>
    </div>

    <div class="row">
            <div class="col-md-4 mt-4"></div>

        <form class="col-md-7" method="post">
            {% csrf_token %}

        <div class="input-group col-md-8 mb-3">
            <div class="input-group-prepend">
                <div id="header_input_profil" class="input-group-text">Adresse Email</div>
            </div>
            {{ form.email }} 
        </div>
        
        <div class='row'>
                <div class="col-md-3 mt-4"></div>
            <div id="submit_profil1">
                <button type="submit" class="btn btn-success mb-3">Envoyer</button>
            </div>
        </div>

    </form>

    </div>
    
</div>


{% endblock %}

pizzy_project/users/templates/users/signup.html
{% extends "base.html" %}
{% load static %}

{% block css %} "{% static 'app1/css/signup.css' %}" {% endblock css %}

{% block section %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div id="header_signup">
                <div id="titre_signup" class="mb-3"> CREER UN COMPTE </div>
                <div id="text_header_signup" class="mb-3"> Et commencer sur notre site </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-md-3 mt-4"></div>

        <div id="from_signup" class="col-md-9">
            <form method='POST'> {% csrf_token %}

                <div class="input-group mb-3 mt-3">
                    <div class="input-group-prepend">
                        <div id="header_input_signup" class="input-group-text">{{ form.last_name.label }}</div>
                    </div>
                    {{ form.last_name }}
                    <div class='col-md-4'></div>
                </div>

                <div class="input-group mb-3 mt-3">
                    <div class="input-group-prepend">
                        <div id="header_input_signup" class="input-group-text">{{ form.first_name.label }}</div>
                    </div>
                    {{ form.first_name }}
                    <div class='col-md-4'></div>
                </div>

                <div class="input-group mb-3 mt-3">
                    <div class="input-group-prepend">
                        <div id="header_input_signup" class="input-group-text">{{ form.email.label }}</div>
                    </div>
                    {{ form.email }}

                    <div class='col-md-4 password_error'>
                        {% for error in form.email.errors %} {{ error }} {% endfor %}
                    </div>
                </div>

                <div class="input-group mb-3 mt-3">
                    <div class="input-group-prepend">
                        <div id="header_input_signup" class="input-group-text">{{ form.phone_number.label }}</div>
                    </div>
                    {{ form.phone_number }}
                    <div class='col-md-4 password_error'>
                        {% for error in form.phone_number.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div class='row'>
                    <hr style="height: 2px; color: lightgray; background-color: lightgray; width: 400px; border: none;">
                    <div class='col-md-4'></div>
                </div>


                <div class="input-group mb-3 mt-3">
                    <div class="input-group-prepend">
                        <div id="header_input_signup" class="input-group-text">{{ form.username.label }}</div>
                    </div>
                    {{ form.username }}
                    <div class='col-md-4 password_error'>
                        {% for error in form.username.errors %} {{ error }} {% endfor %}
                    </div>
                </div>                

                <div class="input-group mb-3 mt-3">
                    <div class="input-group-prepend">
                        <div id="header_input_signup" class="input-group-text ">{{ form.password1.label }}</div>
                    </div>
                    {{ form.password1 }}
                    <div class='col-md-4'></div>
                </div>

                <div class="input-group mb-3 mt-3">
                    <div class="input-group-prepend">
                        <div id="header_input_signup" class="input-group-text ">{{ form.password2.label }}</div>
                    </div>
                    {{ form.password2 }}
                    <div class='col-md-4 password_error'>
                        {% for error in form.password2.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div class='row'>
                    <div class='col-md-4'></div>

                    <div id="submit_profil1">
                        <button type="submit" class="btn btn-success mb-3">Envoyer</button>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>

{% endblock section %}